//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace nilnul.num.natural.prime.model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PrimeEntities2 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PrimeEntities2 object using the connection string found in the 'PrimeEntities2' section of the application configuration file.
        /// </summary>
        public PrimeEntities2() : base("name=PrimeEntities2", "PrimeEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PrimeEntities2 object.
        /// </summary>
        public PrimeEntities2(string connectionString) : base(connectionString, "PrimeEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PrimeEntities2 object.
        /// </summary>
        public PrimeEntities2(EntityConnection connection) : base(connection, "PrimeEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Prime> Prime
        {
            get
            {
                if ((_Prime == null))
                {
                    _Prime = base.CreateObjectSet<Prime>("Prime");
                }
                return _Prime;
            }
        }
        private ObjectSet<Prime> _Prime;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Prime_CompositeUpperBound> Prime_CompositeUpperBound
        {
            get
            {
                if ((_Prime_CompositeUpperBound == null))
                {
                    _Prime_CompositeUpperBound = base.CreateObjectSet<Prime_CompositeUpperBound>("Prime_CompositeUpperBound");
                }
                return _Prime_CompositeUpperBound;
            }
        }
        private ObjectSet<Prime_CompositeUpperBound> _Prime_CompositeUpperBound;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Prime EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPrime(Prime prime)
        {
            base.AddObject("Prime", prime);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Prime_CompositeUpperBound EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPrime_CompositeUpperBound(Prime_CompositeUpperBound prime_CompositeUpperBound)
        {
            base.AddObject("Prime_CompositeUpperBound", prime_CompositeUpperBound);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<PrimeMaxRecord_Result> PrimeMaxRecord()
        {
            return base.ExecuteFunction<PrimeMaxRecord_Result>("PrimeMaxRecord");
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PrimeModel", Name="Prime")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Prime : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Prime object.
        /// </summary>
        /// <param name="sn">Initial value of the sn property.</param>
        /// <param name="num">Initial value of the num property.</param>
        public static Prime CreatePrime(global::System.Int64 sn, global::System.Int64 num)
        {
            Prime prime = new Prime();
            prime.sn = sn;
            prime.num = num;
            return prime;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 sn
        {
            get
            {
                return _sn;
            }
            set
            {
                if (_sn != value)
                {
                    OnsnChanging(value);
                    ReportPropertyChanging("sn");
                    _sn = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("sn");
                    OnsnChanged();
                }
            }
        }
        private global::System.Int64 _sn;
        partial void OnsnChanging(global::System.Int64 value);
        partial void OnsnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 num
        {
            get
            {
                return _num;
            }
            set
            {
                OnnumChanging(value);
                ReportPropertyChanging("num");
                _num = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("num");
                OnnumChanged();
            }
        }
        private global::System.Int64 _num;
        partial void OnnumChanging(global::System.Int64 value);
        partial void OnnumChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PrimeModel", Name="Prime_CompositeUpperBound")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Prime_CompositeUpperBound : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Prime_CompositeUpperBound object.
        /// </summary>
        /// <param name="val">Initial value of the Val property.</param>
        public static Prime_CompositeUpperBound CreatePrime_CompositeUpperBound(global::System.Int64 val)
        {
            Prime_CompositeUpperBound prime_CompositeUpperBound = new Prime_CompositeUpperBound();
            prime_CompositeUpperBound.Val = val;
            return prime_CompositeUpperBound;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Val
        {
            get
            {
                return _Val;
            }
            set
            {
                if (_Val != value)
                {
                    OnValChanging(value);
                    ReportPropertyChanging("Val");
                    _Val = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Val");
                    OnValChanged();
                }
            }
        }
        private global::System.Int64 _Val;
        partial void OnValChanging(global::System.Int64 value);
        partial void OnValChanged();

        #endregion

    
    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="PrimeModel", Name="PrimeMaxRecord_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class PrimeMaxRecord_Result : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> sn
        {
            get
            {
                return _sn;
            }
            set
            {
                OnsnChanging(value);
                ReportPropertyChanging("sn");
                _sn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sn");
                OnsnChanged();
            }
        }
        private Nullable<global::System.Int64> _sn;
        partial void OnsnChanging(Nullable<global::System.Int64> value);
        partial void OnsnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> num
        {
            get
            {
                return _num;
            }
            set
            {
                OnnumChanging(value);
                ReportPropertyChanging("num");
                _num = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("num");
                OnnumChanged();
            }
        }
        private Nullable<global::System.Int64> _num;
        partial void OnnumChanging(Nullable<global::System.Int64> value);
        partial void OnnumChanged();

        #endregion

    }

    #endregion

    
}
