//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nilnul.num.natural.prime.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class nilnul3Entities : DbContext
    {
    
    
     
    
    
        public nilnul3Entities(string connectionString)
            : base(connectionString)
        {
        }
    
    
     
    
    
    
        public nilnul3Entities()
            : base("name=nilnul3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Prime> Prime { get; set; }
        public virtual DbSet<CompositeCap> CompositeCap { get; set; }
    
        public virtual ObjectResult<sp_PrimeMaxRecord_Result> sp_PrimeMaxRecord()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PrimeMaxRecord_Result>("sp_PrimeMaxRecord");
        }
    }
}
